WFLY-9754 an option to suppress transaction propagation for all beans
wildfly/jboss-ejb-client pull request #453
Opened 2020-03-13 14:25 UTC by istudens

Issue: https://issues.redhat.com/browse/EJBCLIENT-326

This PR supersedes https://github.com/wildfly/jboss-ejb-client/pull/358.

The conflicts of the original PR have been resolved and the code itself has been moved to a new 3.3 schema.

2020-03-13 14:26 UTC, istudens commented
@fl4via @tadamski  could you review please? thanks

2023-08-29 09:21 UTC, jbaesner commented on src/main/java/org/jboss/ejb/client/legacy/JBossEJBProperties.java
> +    private static final String PROPERTY_KEY_SUPPRESS_TX_PROPAGATION = "transaction.propagation.suppress";
This is the _legacy_ `JBossEJBProperties`, is it intended to add new configuration to the old _legacy_ configuration approach?

2023-08-29 09:23 UTC, jbaesner commented on src/main/resources/schema/wildfly-client-ejb_3_1.xsd
> +    <xsd:complexType name="tx-propagation-type">
This block should be in `wildfly-client-ejb_3_3.xsd` only

2023-08-29 13:05 UTC, chengfang commented
@istudens should this PR go toward `main` branch?

2023-11-21 10:49 UTC, tadamski requested changes
@istudens I also think that this PR is against the wrong branch. Could you please check?

2023-11-22 13:14 UTC, tadamski reviewed
closing after discussion with @istudens (out of date)

2023-11-22 13:14 UTC, closed without merging